---
title: Een achtergrond toevoegen vanuit de Scratch-bibliotheek
hero_image: images / banner.png
description: Een achtergrond toevoegen vanuit de Scratch-bibliotheek
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Een achtergrond toevoegen
