title: Adding a backdrop from the Scratch library
hero_image: images/banner.png
subtitle: backdrop-from-library subtitle
description: Adding a backdrop from the Scratch library
published: false

steps:
  - title: Step one
