---
title: स्क्रैच लाइब्रेरी से पृष्ठभूमि(backdrop) जोड़ना
hero_image: images/banner.png
description: स्क्रैच लाइब्रेरी से पृष्ठभूमि(backdrop) जोड़ना
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "“scratch\""
steps:
  - 
    title: पृष्ठभूमि जोड़ना
