---
title: Додавање позадине из библиотеке Сцратцх
hero_image: имагес / баннер.пнг
description: Додавање позадине из библиотеке Сцратцх
theme: цц-прототип
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "огреботина"
steps:
  - 
    title: Додавање позадине
