---
title: Legger til et bakteppe fra Scratch-biblioteket
hero_image: images / banner.png
description: Legger til et bakteppe fra Scratch-biblioteket
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "ripe"
steps:
  - 
    title: Legger til et bakteppe
