---
title: Einen Hintergrund aus der Scratch-Bibliothek hinzufügen
hero_image: Bilder / Banner.png
description: Einen Hintergrund aus der Scratch-Bibliothek hinzufügen
theme: cc-Prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "kratzen"
steps:
  - 
    title: Hinzufügen eines Hintergrunds
