---
title: Thêm phông nền từ thư viện Scratch
hero_image: images / banner.png
description: Thêm phông nền từ thư viện Scratch
theme: nguyên mẫu cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "vết trầy"
steps:
  - 
    title: Thêm phông nền
