---
title: Aggiunta di uno sfondo dalla libreria Scratch
hero_image: images / banner.png
description: Aggiunta di uno sfondo dalla libreria Scratch
theme: cc-prototipo
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "graffiare"
steps:
  - 
    title: Aggiungere uno sfondo
