---
title: Tilføjelse af en baggrund fra Scratch-biblioteket
hero_image: images/banner.png
description: Tilføjelse af en baggrund fra Scratch-biblioteket
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Tilføjelse af en baggrund
