---
title: Добавяне на фон от библиотеката Scratch
hero_image: изображения / banner.png
description: Добавяне на фон от библиотеката Scratch
theme: сс-прототип
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "драскотина"
steps:
  - 
    title: Добавяне на фон
