---
title: Dodavanje pozadine iz Scratch knjižnice
hero_image: images/banner.png
description: Dodavanje pozadine iz Scratch knjižnice
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Dodavanje pozadine
