---
title: Taustan kääntäminen Scratch-kirjastosta
hero_image: Kuvien / banner.png
description: Taustan kääntäminen Scratch-kirjastosta
theme: CC-prototyyppi
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "naarmu"
steps:
  - 
    title: Taustan lisääminen
