---
title: Adding a backdrop from the Scratch library
hero_image: Kuvien / banner.png
description: Adding a backdrop from the Scratch library
theme: CC-prototyyppi
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "naarmu"
steps:
  - 
    title: Adding a backdrop
