---
title: Taustan lisääminen Scratch-kirjastosta
hero_image: images/banner.png
description: Taustan lisääminen Scratch-kirjastosta
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Taustan lisääminen
