---
title: اضافه کردن پشت صحنه جدید از کتابخانه ی اسکرچ
hero_image: images/banner.png
description: اضافه کردن پشت صحنه جدید از کتابخانه ی اسکرچ
theme: نمونه اولیه cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "خراش"
steps:
  - 
    title: اضافه کردن پشت صحنه
