---
title: Ychwanegu cefndir o lyfrgell Scratch
hero_image: delweddau / banner.png
description: Ychwanegu cefndir o lyfrgell Scratch
theme: cc-prototeip
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "crafu"
steps:
  - 
    title: Ychwanegu cefndir
