---
title: Agregar un fondo de la biblioteca Scratch
hero_image: images / banner.png
description: Agregar un fondo de la biblioteca Scratch
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Agregar un fondo
