---
title: Einen Hintergrund aus der Scratch-Bibliothek hinzufügen
hero_image: images/banner.png
description: Einen Hintergrund aus der Scratch-Bibliothek hinzufügen
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Hinzufügen eines Hintergrunds
