---
title: Adăugarea unui fundal din biblioteca Scratch
hero_image: images/banner.png
description: Adăugarea unui fundal din biblioteca Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adăugarea unui fundal
