---
title: Adăugarea unui decor din biblioteca Scratch
hero_image: images / banner.png
description: Adăugarea unui decor din biblioteca Scratch
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Adăugarea unui decor
