---
title: Adicionando um pano de fundo da biblioteca Scratch
hero_image: images/banner.png
description: Adicionando um pano de fundo da biblioteca Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Adicionando um pano de fundo
