---
title: Menambahkan latar dari pustaka Scratch
hero_image: images/banner.png
description: Menambahkan latar dari pustaka Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Menambahkan latar
