---
title: Menambahkan latar belakang dari perpustakaan Scratch
hero_image: gambar / banner.png
description: Menambahkan latar belakang dari perpustakaan Scratch
theme: cc-prototipe
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Menambahkan latar belakang
