---
title: Dodajanje ozadja iz knjižnice Scratch
hero_image: images / banner.png
description: Dodajanje ozadja iz knjižnice Scratch
theme: cc-prototip
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "praska"
steps:
  - 
    title: Dodajanje ozadja
