---
title: Adding a backdrop from the Scratch library
hero_image: תמונות / banner.png
description: Adding a backdrop from the Scratch library
theme: אב טיפוס
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "שריטה"
steps:
  - 
    title: Adding a backdrop
