---
title: Háttér hozzáadása a Scratch könyvtárból
hero_image: images/banner.png
description: Háttér hozzáadása a Scratch könyvtárból
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Háttér hozzáadása
