---
title: Fekete háttér hozzáadása a Scratch könyvtárból
hero_image: images / banner.png
description: Fekete háttér hozzáadása a Scratch könyvtárból
theme: cc-prototípus
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "karcolás"
steps:
  - 
    title: Háttér hozzáadása
