---
title: 從Scratch庫中添加背景
hero_image: 圖片/ banner.png
description: 從Scratch庫中添加背景
theme: CC-原型
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "刮"
steps:
  - 
    title: 添加背景
