---
title: Adding a backdrop from the Scratch library
hero_image: 圖片/ banner.png
description: Adding a backdrop from the Scratch library
theme: CC-原型
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "刮"
steps:
  - 
    title: Adding a backdrop
