---
title: Ajouter une toile de fond à partir de la bibliothèque Scratch
hero_image: images / banner.png
description: Ajouter une toile de fond à partir de la bibliothèque Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "rayure"
steps:
  - 
    title: Ajouter une toile de fond
