---
title: Adding a backdrop from the Scratch library
hero_image: images / banner.png
description: Adding a backdrop from the Scratch library
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "rayure"
steps:
  - 
    title: Adding a backdrop
