---
title: Agregar un fondo de la biblioteca de Scratch
hero_image: images/banner.png
description: Agregar un fondo de la biblioteca de Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Agregar un fondo
