---
title: إضافة خلفية من مكتبة Scratch
hero_image: images/banner.png
description: إضافة خلفية من مكتبة Scratch
theme: "cc-prototype\n"
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: إضافة خلفية
