---
title: Dodawanie tła z biblioteki Scratcha
hero_image: images / banner.png
description: Dodawanie tła z biblioteki Scratcha
theme: prototyp cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Dodawanie tła
