---
title: Pridanie pozadia z knižnice Scratch
hero_image: images / banner.png
description: Pridanie pozadia z knižnice Scratch
theme: cc-prototyp
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "škrabanec"
steps:
  - 
    title: Pridávanie pozadia
