---
title: Lägga till bakgrund från Scratch-biblioteket
hero_image: images / banner.png
description: Lägga till bakgrund från Scratch-biblioteket
theme: cc-prototyp
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "repa"
steps:
  - 
    title: Lägger till en bakgrund
