---
title: Menambah latar belakang dari perpustakaan Scratch
hero_image: imej / banner.png
description: Menambah latar belakang dari perpustakaan Scratch
theme: prototaip cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "awal"
steps:
  - 
    title: Menambah latar belakang
