---
title: Adding a backdrop from the Scratch library
hero_image: imej / banner.png
description: Adding a backdrop from the Scratch library
theme: prototaip cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "awal"
steps:
  - 
    title: Adding a backdrop
