---
title: Dodavanje pozadine iz Scratch biblioteke
hero_image: images/banner.png
description: Dodavanje pozadine iz Scratch biblioteke
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodavanje pozadine
