---
title: Ajouter un arrière plan à partir de la bibliothèque Scratch
hero_image: images/banner.png
description: Ajouter un arrière plan à partir de la bibliothèque Scratch
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Ajouter un arrière plan
