---
title: Aggiungere uno sfondo dalla libreria di Scratch
hero_image: images/banner.png
description: Aggiungere uno sfondo dalla libreria di Scratch
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Aggiungere uno sfondo
