---
title: Scratch k端t端phanesinden bir dekor ekleme
hero_image: images / banner.png
description: Scratch k端t端phanesinden bir dekor ekleme
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Bir dekor ekleme
