---
title: Scratch kütüphanesinden bir fon ekleme
hero_image: images / banner.png
description: Scratch kütüphanesinden bir fon ekleme
theme: cc-prototip
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "çizik"
steps:
  - 
    title: Bir arka plan ekleme
